version: '3.7'
services:
  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    environment:
      WORDPRESS_DB_HOST: mysql1:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
    ports:
      - "8081:80"
    networks:
      - wordpress_network
    depends_on:
      - mysql1

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    environment:
      WORDPRESS_DB_HOST: mysql2:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
    ports:
      - "8082:80"
    networks:
      - wordpress_network
    depends_on:
      - mysql2

  mysql1:
    image: mysql:8.0
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    networks:
      - wordpress_network

  mysql2:
    image: mysql:8.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    networks:
      - wordpress_network

  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
